name: Scheduled Maintenance
on:
  schedule:
    # Every 5 minutes for maintenance
    - cron: '*/5 * * * *'
    # Daily purge at 03:10 UTC
    - cron: '10 3 * * *'
  workflow_dispatch: # Allow manual trigger

env:
  SERVICE_URL: ${{ secrets.SERVICE_URL }}
  ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}

jobs:
  maintenance:
    runs-on: ubuntu-latest
    if: github.event.schedule == '*/5 * * * *' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Run maintenance tasks
        run: |
          response=$(curl -s -w "%{http_code}" -X POST "$SERVICE_URL/admin/maintain" \
            -H "X-Admin-Token: $ADMIN_TOKEN" \
            -H "Content-Type: application/json")
          http_code="${response: -3}"
          if [ "$http_code" != "200" ]; then
            echo "Maintenance failed with status $http_code"
            exit 1
          fi
          echo "Maintenance completed successfully"

  purge:
    runs-on: ubuntu-latest
    if: github.event.schedule == '10 3 * * *' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Run daily purge
        run: |
          response=$(curl -s -w "%{http_code}" -X POST "$SERVICE_URL/admin/purge" \
            -H "X-Admin-Token: $ADMIN_TOKEN" \
            -H "Content-Type: application/json")
          http_code="${response: -3}"
          if [ "$http_code" != "200" ]; then
            echo "Purge failed with status $http_code"
            exit 1
          fi
          echo "Purge completed successfully"